# Generated by Django 5.0.6 on 2024-06-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cancion',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=90)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nac', models.DateField()),
                ('cuenta_vigente', models.BooleanField()),
                ('genero', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ListaCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cancion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente')),
            ],
            options={
                'db_table': 'lista_cancion',
                'unique_together': {('cliente', 'cancion')},
            },
        ),
    ]
