# Generated by Django 5.0.6 on 2024-06-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField()),
                ('resenya', models.CharField(max_length=1000)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente')),
            ],
        ),
    ]
