# Generated by Django 5.0.6 on 2024-06-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0002_resenya'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resenya',
            table='resenya',
        ),
    ]
