# Generated by Django 5.0.6 on 2024-06-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0003_alter_resenya_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenya',
            name='resenya',
            field=models.TextField(max_length=1000),
        ),
    ]
