# Generated by Django 5.0.6 on 2024-06-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0005_alter_resenya_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenya',
            name='puntuacion',
            field=models.FloatField(),
        ),
    ]
