# Generated by Django 5.0.6 on 2024-06-13 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0008_alter_resenya_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenya',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, help_text='Puntuación entre 1 y 5', max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
