# Generated by Django 5.0.6 on 2024-06-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0009_alter_resenya_puntuacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resenya',
            unique_together={('cliente', 'resenya')},
        ),
    ]
