# Generated by Django 5.0.6 on 2024-06-14 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0011_alter_resenya_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='temp_images/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente')),
            ],
            options={
                'db_table': 'imagen_cliente',
            },
        ),
    ]
