# Generated by Django 5.0.6 on 2024-06-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0012_imagencliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencliente',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente'),
        ),
        migrations.AlterField(
            model_name='resenya',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente'),
        ),
    ]
