# Generated by Django 5.0.6 on 2024-06-18 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0014_alter_imagencliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenya',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente', unique=True),
        ),
    ]
